version: 2
jobs:
  build:
    docker:
      #specify the version you desire here
      - image: circleci/python3.7.7

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache requirements
      -restore_cache:
        keys:
          - v1-dependancies-{{ checksum "pollsapi/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependancies-

      -run:
        name: install dependancies
        command: |
          . venv/bin/activate
            cd pollsapi
            python manage.py test
      -store_artifacts:
        path: test-reports
        destibation: test-reports